spring:
    profiles:
       active: dev
    http:
       multipart:
          max-file-size: 2MB
          max-request-size: 2MB
    jackson:
       time-zone: GMT+8
       date-format: yyyy-MM-dd HH:mm:ss