datasource:
    playAdminDb:
        url: jdbc:mysql://10.0.3.105:3306/game_service?autoReconnect=true&failOverReadOnly=false&characterEncoding=utf-8&useUnicode=true&zeroDateTimeBehavior=convertToNull
        username: root
        password: 123456
        driverClassName: com.mysql.jdbc.Driver