datasource:
    playAdminDb:
        url: jdbc:mysql://localhost:3306/accompany_play_db?autoReconnect=true&failOverReadOnly=false&characterEncoding=utf-8&useUnicode=true&zeroDateTimeBehavior=convertToNull
        username: root
        password: ''
        driverClassName: com.mysql.jdbc.Driver