spring:
    thymeleaf:
       cache: false
       mode: LEGACYHTML5

play:
  wechat:
    appId: 111
    secret: 111
    token: 111
    aesKey: 111
    msgDataFormat: JSON
    mchId:
    mchKey:
    subAppId:
    subMchId:
    keyPath: