spring:
    profiles:
       active: dev
play:
  wechat:
    appId: wxf0bf670601a34bb5
    secret: d8aeb8dc6265394a3789aff6b2792a23
    token: 111
    aesKey: 111
    msgDataFormat: JSON
    mchId:
    mchKey:
    subAppId:
    subMchId:
    keyPath: